name: Run USDT Query

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-query:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download executable
        run: |
          wget https://github.com/web3-interaction-examples/go-query-usdt-issue/releases/download/v1.0.0/go-query-usdt-issue-linux-amd64
          chmod +x go-query-usdt-issue-linux-amd64
      
      - name: Run query
        run: ./go-query-usdt-issue-linux-amd64 
